---

# Main tasks file for airflow role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::airflow'
    - 'role::airflow::init'
    - 'role::airflow::install'


# Installation tasks management
- name: 'INSTALL | Include installation tasks'
  include: "{{ role_path }}/tasks/manage_installation.yml"
  tags:
    - 'role::airflow'
    - 'role::airflow::install'


# Configuration tasks management
- name: 'CONFIG | Include configuration tasks'
  include: "{{ role_path }}/tasks/manage_configuration.yml"
  tags:
    - 'role::airflow'
    - 'role::airflow::config'


# Services tasks management
- name: 'SERVICE | Include services configuration tasks'
  include: "{{ role_path }}/tasks/manage_services.yml"
  become: True
  tags:
    - 'role::airflow'
    - 'role::airflow::config'
    - 'role::airflow::install'
