---

# Airflow configuration tasks

# Manage configuration templating
- name: 'Manage configuration templating'
  become: True
  become_user: "{{ airflow_user_name }}"
  template:
    src: "{{ role_path }}/templates/airflow.cfg.j2"
    dest: "{{ airflow_config.core.home }}/airflow.cfg"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_group }}"
    mode: '0400'


# Manage logs folder
- name: 'Manage log folder'
  become: True
  file:
    path: "{{ airflow_log_path }}"
    owner: "{{ airflow_log_owner }}"
    group: "{{ airflow_log_group }}"
    mode: "{{ airflow_log_mode }}"
    state: 'directory'


# Manage logrotate configuration
- name: 'Manage logrotate configuration'
  become: True
  template:
    src: "{{ role_path }}/templates/logrotate.j2"
    dest: "{{ item.filename }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ airflow_logrotate_config }}"
