---

# Airflow services management

- name: 'Manage webserver service with upstart'
  become: True
  template:
    src: "{{ role_path }}/templates/upstart/airflow-webserver.conf.j2"
    dest: '/etc/init/airflow-webserver.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart airflow-webserver'
  when: "{{ 'airflow-scheduler' in airflow_managed_upstart_services }}"


- name: 'Manage scheduler service with upstart'
  become: True
  template:
    src: "{{ role_path }}/templates/upstart/airflow-scheduler.conf.j2"
    dest: '/etc/init/airflow-scheduler.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart airflow-scheduler'
  when: "{{ 'airflow-scheduler' in airflow_managed_upstart_services }}"


# Services states
- name: 'Manage airflow services states'
  become: True
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ airflow_services_states }}"
